select * from customer limit 20

--01.What is total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue 
from customer
group by gender
--02.which customers used discount but still spent more than the avaearage purchase amount?
select customer_id,purchase_amount from customer
where discount_applied='Yes' and 
purchase_amount>(select avg(purchase_amount) from customer)
--03.which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2)as "top_product_review"  ----here we used numerid beacause review rating column is double precision to use round function we have to use numeric
from customer 
group by item_purchased 
order by avg(review_rating) desc
limit 5
--04.compare the average purchase amount between standard and express shipping.
select avg(purchase_amount) as average_purchase_amount,shipping_type from customer 
where shipping_type in('Express','Standard')
group by shipping_type 
--05.do subscribed customers spend more? compare avaerage spend and total revenue between subscribers and non-subscribers.
select subscription_status,round(avg(purchase_amount),2)as average_revenue_generated,
round(sum(purchase_amount),2) as total_revenue_generated from customer 
where subscription_status in ('Yes','No')
group by subscription_status
--06.which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;
--07.segment customers into new,returning, and loyal based on their total number of previous purchases and show the count of each segment.
with customer_type as(                          ----WITH clause is used to define temporary named result sets that can be referenced 
                                                ----within single select,update,delete,insert
select customer_id,previous_purchases,
case
    WHEN previous_purchases=1 then 'NEW CUSTOMER'
	WHEN previous_purchases between 2 and 10 then 'RETURNING CUSTOMER'
	else 'LOYAL CUSTOMER'
	end as customer_segment
from customer
)
select customer_segment,count(*) as "number of customeres"
from customer_type
group by customer_segment
--08.What are the top 3 most purchased products within each category?
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count (customer_id)desc)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;
--09.are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status
--10.what is revenue contribution of each age group?
select age_group,sum(purchase_amount) as revenue_generated
from customer
group by age_group
order by revenue_generated desc



